/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import wspacote.ClassNotFoundException_Exception;
import wspacote.SQLException_Exception;

/**
 *
 * @author junior
 */
public class TelaTed extends javax.swing.JFrame {

    /**
     * Creates new form TelaTed
     */
    public TelaTed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoCodTed = new javax.swing.JTextField();
        campoValorTed = new javax.swing.JTextField();
        buttonTED = new javax.swing.JButton();
        CBoxJ = new javax.swing.JCheckBox();
        CBoxR = new javax.swing.JCheckBox();
        CBoxS = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        campoSelecaoRafael = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonMenu.setText("Voltar M.Principal");
        buttonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite o código da conta:");

        jLabel2.setText("Digite o valor:");

        campoCodTed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodTedActionPerformed(evt);
            }
        });

        campoValorTed.setToolTipText("");
        campoValorTed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorTedActionPerformed(evt);
            }
        });

        buttonTED.setText("Realizar TED");
        buttonTED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTEDActionPerformed(evt);
            }
        });

        CBoxJ.setText("WebService Junior");
        CBoxJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxJActionPerformed(evt);
            }
        });

        CBoxR.setText("WebService Eduardo");
        CBoxR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxRActionPerformed(evt);
            }
        });

        CBoxS.setText("WebService Sdayle");
        CBoxS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxSActionPerformed(evt);
            }
        });

        jLabel4.setText("Selecione o WebService :");

        campoSelecaoRafael.setText("WebService Rafael");
        campoSelecaoRafael.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSelecaoRafaelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(buttonMenu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoCodTed, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBoxJ)
                            .addComponent(CBoxR)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(campoSelecaoRafael)
                                .addComponent(CBoxS)))))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(campoValorTed, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(buttonTED)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(campoCodTed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CBoxJ)))
                .addGap(18, 18, 18)
                .addComponent(CBoxR)
                .addGap(18, 18, 18)
                .addComponent(CBoxS)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoSelecaoRafael))
                .addGap(18, 18, 18)
                .addComponent(campoValorTed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(buttonMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTEDActionPerformed
        // TODO add your handling code here:
        
       
              
        String codigo =campoCodTed.getText();
       
        String valor= campoValorTed.getText();
        String valorSdayle =campoValorTed.getText();
        
        
       
        Double valor2  = Double.parseDouble(valor);
          Double valorSdayle2  = Double.parseDouble(valorSdayle);
        
        
        
            if(CBoxJ.isSelected()){
            try {
            String resultado = "";
            resultado= ted("", codigo, valor2);
            JOptionPane.showMessageDialog(null, resultado);
            campoCodTed.setText("");
                  
                  campoValorTed.setText("");
            
            
        } catch (ClassNotFoundException_Exception ex) {
            Logger.getLogger(TelaTed.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException_Exception ex) {
            Logger.getLogger(TelaTed.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
         if(CBoxS.isSelected()){
            
             
             String resultado1 = "";
             
            
             resultado1= ted_1(codigo,valorSdayle2);
             JOptionPane.showMessageDialog(null, resultado1);
             campoCodTed.setText("");
                
                  campoValorTed.setText("");
         }
             
         
              if(CBoxR.isSelected()){
                  String resultado = "";
                  resultado= ted_2(codigo,valor2);
                  JOptionPane.showMessageDialog(null, resultado);
                  campoCodTed.setText("");
                 
                  campoValorTed.setText("");
             }
              
              if(campoSelecaoRafael.isSelected()){
                  String resultadoRafael ="";
                  resultadoRafael= ted_3(codigo, valor2);
                  JOptionPane.showMessageDialog(null, resultadoRafael);
                  campoCodTed.setText("");
               
                  campoValorTed.setText("");
                  
              }
              
                  
              
        
              
         
    }//GEN-LAST:event_buttonTEDActionPerformed

    private void buttonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuActionPerformed
        // TODO add your handling code here:
         new Inicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonMenuActionPerformed

    private void campoValorTedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorTedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorTedActionPerformed

    private void CBoxJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxJActionPerformed
        // TODO add your handling code here:
        CBoxR.setSelected(false);
        CBoxS.setSelected(false);
        campoSelecaoRafael.setSelected(false);
    }//GEN-LAST:event_CBoxJActionPerformed

    private void CBoxRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxRActionPerformed
        // TODO add your handling code here:
        CBoxJ.setSelected(false);
        CBoxS.setSelected(false);
        campoSelecaoRafael.setSelected(false);
    }//GEN-LAST:event_CBoxRActionPerformed

    private void CBoxSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxSActionPerformed
        // TODO add your handling code here:
        CBoxR.setSelected(false);
        CBoxJ.setSelected(false);
        campoSelecaoRafael.setSelected(false);
       
    }//GEN-LAST:event_CBoxSActionPerformed

    private void campoSelecaoRafaelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSelecaoRafaelActionPerformed
        // TODO add your handling code here:
        CBoxR.setSelected(false);
        CBoxJ.setSelected(false);
        CBoxS.setSelected(false);
    }//GEN-LAST:event_campoSelecaoRafaelActionPerformed

    private void campoCodTedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodTedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodTedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBoxJ;
    private javax.swing.JCheckBox CBoxR;
    private javax.swing.JCheckBox CBoxS;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonMenu;
    private javax.swing.JButton buttonTED;
    private javax.swing.JTextField campoCodTed;
    private javax.swing.JCheckBox campoSelecaoRafael;
    private javax.swing.JTextField campoValorTed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private static String ted(java.lang.String codigo, java.lang.String nome, double valor) throws SQLException_Exception, ClassNotFoundException_Exception {
        wspacote.WSJoseM_Service service = new wspacote.WSJoseM_Service();
        wspacote.WSJoseM port = service.getWSJoseMPort();
        return port.ted(codigo, nome, valor);
    }

    private static String ted_1(java.lang.String arg0, double arg1) {
        cliente.sdayle.ImplService service = new cliente.sdayle.ImplService();
        cliente.sdayle.Servico port = service.getImplPort();
        return port.ted(arg0, arg1);
    }

    private static String ted_2(java.lang.String codigo, double valor) {
        clientes.eduardo.WSEduardo service = new clientes.eduardo.WSEduardo();
        clientes.eduardo.WSEduardoSoap port = service.getWSEduardoSoap();
        return port.ted(codigo, valor);
    }

    private static String ted_3(java.lang.String codigo, double valor) {
        clientes.rafael.WSRafael_Service service = new clientes.rafael.WSRafael_Service();
        clientes.rafael.WSRafael port = service.getWSRafaelPort();
        return port.ted(codigo, valor);
    }

    

    
    }



