/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import cliente.sdayle.Correntista;
import clientes.eduardo.ObjectC;
import clientes.rafael.Co;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import wspacote.ClassNotFoundException_Exception;
import wspacote.ObjetoC;
import wspacote.SQLException_Exception;

/**
 *
 * @author junior
 */
public class TelaRetornaOBJ extends javax.swing.JFrame {

    /**
     * Creates new form TelaRetornaOBJ
     */
    public TelaRetornaOBJ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonConsultar = new javax.swing.JButton();
        CBoxJOBJ = new javax.swing.JCheckBox();
        CBoxROBJ = new javax.swing.JCheckBox();
        CBoxSOBJ = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        campoCodOBJ = new javax.swing.JTextField();
        campoSelecaoRafael = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonConsultar.setText("Consultar");
        buttonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultarActionPerformed(evt);
            }
        });

        CBoxJOBJ.setText("WebService Junior");
        CBoxJOBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxJOBJActionPerformed(evt);
            }
        });

        CBoxROBJ.setText("WebService Eduardo");
        CBoxROBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxROBJActionPerformed(evt);
            }
        });

        CBoxSOBJ.setText("WebService Sdayle");
        CBoxSOBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxSOBJActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione um servidor:");

        jLabel2.setText("Código Usuário");

        jButton2.setText("Voltar Menu Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        campoCodOBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodOBJActionPerformed(evt);
            }
        });

        campoSelecaoRafael.setText("WebService Rafael");
        campoSelecaoRafael.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSelecaoRafaelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoCodOBJ, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(buttonConsultar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CBoxJOBJ)
                        .addComponent(CBoxROBJ))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(campoSelecaoRafael)
                        .addComponent(CBoxSOBJ)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCodOBJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(buttonConsultar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBoxJOBJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBoxROBJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBoxSOBJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSelecaoRafael)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBoxSOBJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxSOBJActionPerformed
        // TODO add your handling code here:
        CBoxJOBJ.setSelected(false);
        CBoxROBJ.setSelected(false);
        campoSelecaoRafael.setSelected(false);
    }//GEN-LAST:event_CBoxSOBJActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Inicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultarActionPerformed
        // TODO add your handling code here:
        if(CBoxJOBJ.isSelected()){
               String codigoJunior="";
                codigoJunior=  campoCodOBJ.getText();
                
                ObjetoC resultado = null;
            try {
                resultado = correntistaOp(codigoJunior);
            } catch (ClassNotFoundException_Exception ex) {
                Logger.getLogger(TelaRetornaOBJ.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException_Exception ex) {
                Logger.getLogger(TelaRetornaOBJ.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(resultado==null){
                JOptionPane.showMessageDialog(null, "Usuário inexistente");
                
            }
            else{
                   try {
                       
                       JOptionPane.showMessageDialog(null,"Código:"+ correntistaOp(codigoJunior).getCodigo()+"  |     Nome: "+correntistaOp(codigoJunior).getNome()+" |     Valor: "+ correntistaOp(codigoJunior).getValor());
                       campoCodOBJ.setText("");
                   } catch (ClassNotFoundException_Exception ex) {
                       Logger.getLogger(TelaRetornaOBJ.class.getName()).log(Level.SEVERE, null, ex);
                   } catch (SQLException_Exception ex) {
                       Logger.getLogger(TelaRetornaOBJ.class.getName()).log(Level.SEVERE, null, ex);
                   }
                
            }
                
            
        }
        if(CBoxROBJ.isSelected()){
            String codigoEdu="";
            codigoEdu = campoCodOBJ.getText();
            correntista(codigoEdu);
            if( correntista(codigoEdu)==null){
                 JOptionPane.showMessageDialog(null, "Usuário inexistente");
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Código:"+ correntista(codigoEdu).getCodigo()+"  |     Nome: "+correntista(codigoEdu).getNome()+" |     Valor: "+ correntista(codigoEdu).getValor());
                campoCodOBJ.setText("");
                
            }
            
            
            
            
            
        }
        if(CBoxSOBJ.isSelected()){
            String codigoSdayle="";
                codigoSdayle=  campoCodOBJ.getText();
                Correntista resultadoSdayle =null;
                resultadoSdayle = returnObj(codigoSdayle);
                if(resultadoSdayle==null){
                JOptionPane.showMessageDialog(null, "Usuário inexistente");
                
            }
                else{
                    JOptionPane.showMessageDialog(null,"Código:"+ returnObj(codigoSdayle).getCodigo()+"  |     Nome: "+returnObj(codigoSdayle).getNome()+" |     Valor: "+ returnObj(codigoSdayle).getValor());
                    campoCodOBJ.setText("");
                
            }}
                
                if(campoSelecaoRafael.isSelected()){
                    
                    String codigoRafael ="";
                    Co resultadoRafael =null;
                     codigoRafael = campoCodOBJ.getText();
                    resultadoRafael= correntista_1(codigoRafael);
                
                    if(correntista_1(codigoRafael)==null){
                        JOptionPane.showMessageDialog(null, "Usuário inexistente");
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Código:"+ correntista_1(codigoRafael).getCodigo()+"  |     Nome: "+correntista_1(codigoRafael).getNome()+" |     Valor: "+ correntista_1(codigoRafael).getValor());
                    campoCodOBJ.setText("");
                        
                    }
                
                
    
            
            
        }
    }//GEN-LAST:event_buttonConsultarActionPerformed

    private void campoCodOBJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodOBJActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_campoCodOBJActionPerformed

    private void CBoxJOBJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxJOBJActionPerformed
        // TODO add your handling code here:
        CBoxROBJ.setSelected(false);
        CBoxSOBJ.setSelected(false);
        campoSelecaoRafael.setSelected(false);
        
    }//GEN-LAST:event_CBoxJOBJActionPerformed

    private void CBoxROBJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxROBJActionPerformed
        // TODO add your handling code here:
        CBoxJOBJ.setSelected(false);
        CBoxSOBJ.setSelected(false);
        campoSelecaoRafael.setSelected(false);
    }//GEN-LAST:event_CBoxROBJActionPerformed

    private void campoSelecaoRafaelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSelecaoRafaelActionPerformed
        // TODO add your handling code here:
        CBoxJOBJ.setSelected(false);
        CBoxSOBJ.setSelected(false);
        CBoxROBJ.setSelected(false);
    }//GEN-LAST:event_campoSelecaoRafaelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRetornaOBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRetornaOBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRetornaOBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRetornaOBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRetornaOBJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBoxJOBJ;
    private javax.swing.JCheckBox CBoxROBJ;
    private javax.swing.JCheckBox CBoxSOBJ;
    private javax.swing.JButton buttonConsultar;
    private javax.swing.JTextField campoCodOBJ;
    private javax.swing.JCheckBox campoSelecaoRafael;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private static ObjetoC correntistaOp(java.lang.String codigo) throws ClassNotFoundException_Exception, SQLException_Exception {
        wspacote.WSJoseM_Service service = new wspacote.WSJoseM_Service();
        wspacote.WSJoseM port = service.getWSJoseMPort();
        return port.correntistaOp(codigo);
    }

    private static Correntista returnObj(java.lang.String arg0) {
        cliente.sdayle.ImplService service = new cliente.sdayle.ImplService();
        cliente.sdayle.Servico port = service.getImplPort();
        return port.returnObj(arg0);
    }

    private static ObjectC correntista(java.lang.String codigo) {
        clientes.eduardo.WSEduardo service = new clientes.eduardo.WSEduardo();
        clientes.eduardo.WSEduardoSoap port = service.getWSEduardoSoap();
        return port.correntista(codigo);
    }

    private static Co correntista_1(java.lang.String codigo) {
        clientes.rafael.WSRafael_Service service = new clientes.rafael.WSRafael_Service();
        clientes.rafael.WSRafael port = service.getWSRafaelPort();
        return port.correntista(codigo);
    }

   

    
    
}
